// EIS Grade 8 / IB MYP Year 3 Mathematics curriculum bank.
// Schema mirrors the structure used by the lesson renderer, AI generator
// and Firestore types so a question, a generated lesson and a teacher
// upload all share one shape.

export type CurriculumUnit = 'numerical' | 'abstract' | 'spatial' | 'data';

export type ThreeDType =
  | 'pythagoras_3d'
  | 'equation_balance_3d'
  | 'linear_graph_3d'
  | 'circle_lab_3d'
  | 'ratio_mixer_3d'
  | 'solid_geometry_3d'
  | 'angle_lab_3d'
  | 'probability_spinner_3d'
  | 'percentage_bar_3d'
  | 'data_visualisation_3d';

export type Difficulty = 'core' | 'support' | 'extension';

export type CurriculumQuestion = {
  id: string;
  unit: CurriculumUnit;
  unitLabel: string;
  strand: string;
  topic: string;
  title: string;
  inquiryQuestion: string;
  objective: string;
  prompt: string;
  question: string;
  expectedAnswer: string;
  acceptedKeywords: string[];
  correctFeedback: string;
  partialFeedback: string;
  teacherNote: string;
  threeDType: ThreeDType;
  difficulty: Difficulty;
};

export const unitLabels: Record<CurriculumUnit, string> = {
  numerical: 'Numerical Reasoning',
  abstract: 'Abstract Reasoning',
  spatial: 'Spatial Reasoning',
  data: 'Reasoning with Data',
};

export const threeDLabels: Record<ThreeDType, string> = {
  pythagoras_3d: 'Pythagoras 3D',
  equation_balance_3d: 'Equation Balance 3D',
  linear_graph_3d: 'Linear Graph 3D',
  circle_lab_3d: 'Circle Lab 3D',
  ratio_mixer_3d: 'Ratio Mixer 3D',
  solid_geometry_3d: 'Solid Geometry 3D',
  angle_lab_3d: 'Angle Lab 3D',
  probability_spinner_3d: 'Probability Spinner 3D',
  percentage_bar_3d: 'Percentage Bar 3D',
  data_visualisation_3d: 'Data Visualisation 3D',
};

export const grade8Curriculum: CurriculumQuestion[] = [
  // ─── ABSTRACT REASONING ─────────────────────────────────────────────
  {
    id: 'abstract-linear-equation-balance',
    unit: 'abstract',
    unitLabel: unitLabels.abstract,
    strand: 'Algebra',
    topic: 'Linear equations',
    title: 'Equation Balance Checkpoint',
    inquiryQuestion: 'How do inverse operations keep an equation balanced?',
    objective: 'Solve a two-step linear equation by undoing operations on both sides and justify each move.',
    prompt: 'Treat the equation like a balance: every move on the left must happen on the right.',
    question: 'Solve 5x − 7 = 28 and verify your answer by substitution.',
    expectedAnswer: 'x = 7',
    acceptedKeywords: ['x=7', 'xequals7'],
    correctFeedback: 'Correct. Adding 7 to both sides gives 5x = 35, then dividing by 5 gives x = 7. Substituting back: 5(7) − 7 = 28. ✓',
    partialFeedback: 'Use the balance idea: add 7 to both sides first, then divide by 5. Always check by substituting.',
    teacherNote: 'Reinforce that doing the same operation on both sides keeps the equation true. Connect to the EquationBalance3D scene where weights mirror operations.',
    threeDType: 'equation_balance_3d',
    difficulty: 'core',
  },
  {
    id: 'abstract-linear-with-brackets',
    unit: 'abstract',
    unitLabel: unitLabels.abstract,
    strand: 'Algebra',
    topic: 'Linear equations with brackets',
    title: 'Distribute, then solve',
    inquiryQuestion: 'What does multiplying out a bracket really do?',
    objective: 'Expand single brackets and solve the resulting linear equation.',
    prompt: 'Use the distributive law to remove the bracket, then solve as usual.',
    question: 'Solve 3(2x − 5) = 21.',
    expectedAnswer: 'x = 6',
    acceptedKeywords: ['x=6'],
    correctFeedback: 'Correct. Expanding gives 6x − 15 = 21, so 6x = 36 and x = 6.',
    partialFeedback: 'Multiply 3 into both terms inside the bracket first: 3·2x and 3·(−5). Then balance.',
    teacherNote: 'Common error: forgetting to multiply 3 by −5. Show the bracket as a "group" that everything outside must touch.',
    threeDType: 'equation_balance_3d',
    difficulty: 'core',
  },
  {
    id: 'abstract-linear-variables-both-sides',
    unit: 'abstract',
    unitLabel: unitLabels.abstract,
    strand: 'Algebra',
    topic: 'Linear equations with variables on both sides',
    title: 'Collecting x on one side',
    inquiryQuestion: 'When the variable appears twice, where does it go?',
    objective: 'Solve linear equations with variables on both sides by collecting like terms.',
    prompt: 'Move the variables to one side by adding or subtracting equal amounts on both sides.',
    question: 'Solve 4x + 3 = 2x + 15.',
    expectedAnswer: 'x = 6',
    acceptedKeywords: ['x=6'],
    correctFeedback: 'Correct. Subtracting 2x from both sides: 2x + 3 = 15. Then 2x = 12, so x = 6.',
    partialFeedback: 'First subtract the smaller x-term (2x) from both sides so x appears only once.',
    teacherNote: 'Encourage students to always move the smaller coefficient to keep x positive.',
    threeDType: 'equation_balance_3d',
    difficulty: 'core',
  },
  {
    id: 'abstract-gradient-intercept',
    unit: 'abstract',
    unitLabel: unitLabels.abstract,
    strand: 'Linear relationships',
    topic: 'y = mx + c',
    title: 'Read the gradient and intercept',
    inquiryQuestion: 'What do m and c tell us about a line, before we draw it?',
    objective: 'Identify gradient and y-intercept directly from the equation of a line.',
    prompt: 'Compare the equation to the standard form y = mx + c.',
    question: 'For y = 3x − 5, write down the gradient and the y-intercept.',
    expectedAnswer: 'gradient = 3, y-intercept = −5',
    acceptedKeywords: ['gradient3', 'm=3', 'intercept-5', 'c=-5'],
    correctFeedback: 'Correct. m = 3 means "up 3 for every 1 right". c = −5 means the line crosses the y-axis at (0, −5).',
    partialFeedback: 'The number in front of x is the gradient. The standalone constant is the y-intercept (where x = 0).',
    teacherNote: 'Bring out the geometric meaning: gradient = rise/run, intercept = where the line meets the y-axis.',
    threeDType: 'linear_graph_3d',
    difficulty: 'core',
  },
  {
    id: 'abstract-find-line-from-points',
    unit: 'abstract',
    unitLabel: unitLabels.abstract,
    strand: 'Linear relationships',
    topic: 'Equation of a line from two points',
    title: 'From two points to a line',
    inquiryQuestion: 'How many points define a unique line?',
    objective: 'Find the equation of a line given two points using gradient and substitution.',
    prompt: 'Compute the gradient first, then substitute one point to find c.',
    question: 'A line passes through (1, 4) and (3, 10). Find its equation in the form y = mx + c.',
    expectedAnswer: 'y = 3x + 1',
    acceptedKeywords: ['y=3x+1', '3x+1'],
    correctFeedback: 'Correct. Gradient = (10 − 4) / (3 − 1) = 3. Substituting (1, 4): 4 = 3(1) + c gives c = 1.',
    partialFeedback: 'Use the gradient formula (y₂ − y₁)/(x₂ − x₁). Then substitute one point back to find c.',
    teacherNote: 'Watch sign errors in subtraction. Encourage labelling (x₁, y₁) and (x₂, y₂) clearly.',
    threeDType: 'linear_graph_3d',
    difficulty: 'core',
  },
  {
    id: 'abstract-parallel-perpendicular',
    unit: 'abstract',
    unitLabel: unitLabels.abstract,
    strand: 'Linear relationships',
    topic: 'Parallel and perpendicular lines',
    title: 'Same direction, opposite turn',
    inquiryQuestion: 'What does the gradient tell us about two lines meeting (or never meeting)?',
    objective: 'Use gradients to determine whether two lines are parallel, perpendicular, or neither.',
    prompt: 'Parallel lines share a gradient. Perpendicular gradients multiply to −1.',
    question: 'Line A: y = 2x + 3. Line B: y = −½x + 4. Are they parallel, perpendicular, or neither?',
    expectedAnswer: 'perpendicular',
    acceptedKeywords: ['perpendicular'],
    correctFeedback: 'Correct. m_A × m_B = 2 × (−½) = −1, so the lines meet at a right angle.',
    partialFeedback: 'Multiply the two gradients. If the product is −1, they are perpendicular. If equal, parallel.',
    teacherNote: 'Visualise on grid paper before introducing the −1 rule. The negative reciprocal idea is the leap.',
    threeDType: 'linear_graph_3d',
    difficulty: 'core',
  },
  {
    id: 'abstract-distance-time',
    unit: 'abstract',
    unitLabel: unitLabels.abstract,
    strand: 'Real-world linear graphs',
    topic: 'Distance–time graphs',
    title: 'Reading speed from a graph',
    inquiryQuestion: 'What does a steeper line on a distance–time graph mean?',
    objective: 'Interpret the gradient of a distance–time graph as speed.',
    prompt: 'Use speed = distance ÷ time, which is exactly the gradient.',
    question: 'A cyclist travels 24 km in 1.5 hours at constant speed. What is the gradient (speed) of their distance–time line?',
    expectedAnswer: '16 km/h',
    acceptedKeywords: ['16km/h', '16 km/h', '=16'],
    correctFeedback: 'Correct. 24 ÷ 1.5 = 16 km/h, which is the gradient of the line on a distance–time graph.',
    partialFeedback: 'Gradient = total distance ÷ total time. The units carry through (km per hour).',
    teacherNote: 'Connect "rise over run" with "distance over time". Horizontal sections = stationary; steeper = faster.',
    threeDType: 'linear_graph_3d',
    difficulty: 'core',
  },
  {
    id: 'abstract-quadratic-factorise',
    unit: 'abstract',
    unitLabel: unitLabels.abstract,
    strand: 'Quadratic expressions',
    topic: 'Factorising x² + bx + c',
    title: 'Find the two numbers',
    inquiryQuestion: 'Can every quadratic be written as a product of two brackets?',
    objective: 'Factorise quadratics of the form x² + bx + c by finding two numbers that multiply to c and add to b.',
    prompt: 'Find two numbers whose product is c and whose sum is b.',
    question: 'Solve x² + 5x + 6 = 0 by factorising.',
    expectedAnswer: 'x = −2 or x = −3',
    acceptedKeywords: ['x=-2', 'x=-3', '-2,-3', '-3,-2'],
    correctFeedback: 'Correct. (x + 2)(x + 3) = 0 gives the two roots x = −2 and x = −3.',
    partialFeedback: 'Look for two numbers that multiply to 6 and add to 5. They become the roots (with opposite signs).',
    teacherNote: 'Show the product–sum table. Always set each bracket equal to zero individually.',
    threeDType: 'equation_balance_3d',
    difficulty: 'core',
  },
  {
    id: 'abstract-simultaneous',
    unit: 'abstract',
    unitLabel: unitLabels.abstract,
    strand: 'Linear systems',
    topic: 'Simultaneous equations',
    title: 'Two equations, one solution',
    inquiryQuestion: 'When two straight lines meet, what can their meeting point tell us?',
    objective: 'Solve a pair of simultaneous linear equations using substitution or elimination.',
    prompt: 'Eliminate one variable by adding or subtracting the equations.',
    question: 'Solve the system: 2x + y = 11 and 3x − y = 4.',
    expectedAnswer: 'x = 3, y = 5',
    acceptedKeywords: ['x=3,y=5', 'x=3y=5', '(3,5)'],
    correctFeedback: 'Correct. Adding the equations: 5x = 15, so x = 3. Substituting: 2(3) + y = 11, so y = 5.',
    partialFeedback: 'Add the two equations because the y-terms have opposite signs and will cancel.',
    teacherNote: 'Choose pairs where elimination is one clean addition or subtraction before introducing scaling.',
    threeDType: 'linear_graph_3d',
    difficulty: 'extension',
  },

  // ─── NUMERICAL REASONING ────────────────────────────────────────────
  {
    id: 'numerical-rational-irrational',
    unit: 'numerical',
    unitLabel: unitLabels.numerical,
    strand: 'Number systems',
    topic: 'Rational vs irrational',
    title: 'Classify the number',
    inquiryQuestion: 'What does it mean for a decimal to "never end and never repeat"?',
    objective: 'Identify whether a given number is rational or irrational.',
    prompt: 'A rational number can be written as a fraction of integers. Irrational numbers cannot.',
    question: 'Classify each as rational or irrational: √2, 22/7, 0.333…, π. Which is the only irrational pair?',
    expectedAnswer: '√2 and π are irrational; 22/7 and 0.333… are rational.',
    acceptedKeywords: ['√2andπ', 'sqrt2andpi', 'rootandpi', 'pi', 'irrational'],
    correctFeedback: 'Correct. 22/7 is a fraction; 0.333… = 1/3. √2 and π have non-terminating, non-repeating decimal expansions.',
    partialFeedback: 'A repeating decimal IS rational (you can write it as a fraction). Only non-repeating, non-terminating decimals are irrational.',
    teacherNote: 'Common misconception: students think 22/7 IS π. Stress that 22/7 is a rational approximation.',
    threeDType: 'percentage_bar_3d',
    difficulty: 'core',
  },
  {
    id: 'numerical-recurring-decimal',
    unit: 'numerical',
    unitLabel: unitLabels.numerical,
    strand: 'Number systems',
    topic: 'Recurring decimals',
    title: 'Recurring decimal to fraction',
    inquiryQuestion: 'How can a never-ending decimal possibly equal a fraction?',
    objective: 'Convert a single-digit recurring decimal into its fraction form.',
    prompt: 'Let x equal the decimal, multiply by 10 to shift the digits, then subtract to eliminate the recurrence.',
    question: 'Express 0.4̇ (0.4444…) as a fraction in simplest form.',
    expectedAnswer: '4/9',
    acceptedKeywords: ['4/9'],
    correctFeedback: 'Correct. If x = 0.4̇, then 10x = 4.4̇. Subtracting: 9x = 4, so x = 4/9.',
    partialFeedback: 'Set x equal to the decimal, multiply by 10 (or 100 for two recurring digits), then subtract to remove the recurring part.',
    teacherNote: 'Generalise: a single recurring digit always gives a denominator of 9. Two recurring digits → 99. Etc.',
    threeDType: 'percentage_bar_3d',
    difficulty: 'core',
  },
  {
    id: 'numerical-recurring-decimal-two-digit',
    unit: 'numerical',
    unitLabel: unitLabels.numerical,
    strand: 'Number systems',
    topic: 'Recurring decimals (two digits)',
    title: 'Two recurring digits',
    inquiryQuestion: 'What changes when more than one digit recurs?',
    objective: 'Convert a two-digit recurring decimal to a fraction using the 100× trick.',
    prompt: 'Multiply by 100 (not 10) when two digits recur, then subtract.',
    question: 'Express 0.27̇ (0.272727…) as a fraction in simplest form.',
    expectedAnswer: '3/11',
    acceptedKeywords: ['3/11', '27/99'],
    correctFeedback: 'Correct. 100x − x = 27 gives 99x = 27, so x = 27/99 = 3/11.',
    partialFeedback: 'Multiply by 100 because two digits repeat. Then divide by HCF to simplify the fraction.',
    teacherNote: 'Practise the simplification step — students often stop at 27/99 without reducing.',
    threeDType: 'percentage_bar_3d',
    difficulty: 'extension',
  },
  {
    id: 'numerical-exponents-product',
    unit: 'numerical',
    unitLabel: unitLabels.numerical,
    strand: 'Indices',
    topic: 'Laws of exponents (product)',
    title: 'Multiplying same-base powers',
    inquiryQuestion: 'Why do we add the exponents when multiplying powers of the same number?',
    objective: 'Apply the product rule for powers with the same base.',
    prompt: 'When the bases are equal, add the exponents: aᵐ × aⁿ = aᵐ⁺ⁿ.',
    question: 'Simplify 2³ × 2⁴ and write the result as a power of 2 and as a whole number.',
    expectedAnswer: '2⁷ = 128',
    acceptedKeywords: ['2^7', '2⁷', '=128', '128'],
    correctFeedback: 'Correct. 2³ × 2⁴ = 2³⁺⁴ = 2⁷ = 128.',
    partialFeedback: 'Add the indices because the bases are the same. Then evaluate the resulting power.',
    teacherNote: 'Reinforce why: 2³ means three 2s, 2⁴ means four 2s, so together you have seven 2s multiplied.',
    threeDType: 'percentage_bar_3d',
    difficulty: 'core',
  },
  {
    id: 'numerical-exponents-mixed',
    unit: 'numerical',
    unitLabel: unitLabels.numerical,
    strand: 'Indices',
    topic: 'Combining index laws',
    title: 'Simplify with multiple rules',
    inquiryQuestion: 'Which order should you apply the index laws in?',
    objective: 'Combine product and quotient rules in a single expression.',
    prompt: 'Apply rules from innermost outward: products first, then quotients.',
    question: 'Simplify (2³ × 2⁴) ÷ 2⁵ as a single power of 2 and as a whole number.',
    expectedAnswer: '2² = 4',
    acceptedKeywords: ['2^2', '2²', '=4'],
    correctFeedback: 'Correct. The numerator becomes 2⁷ (3+4); then 2⁷ ÷ 2⁵ = 2⁷⁻⁵ = 2² = 4.',
    partialFeedback: 'Add exponents in the numerator, then subtract for the division: aᵐ ÷ aⁿ = aᵐ⁻ⁿ.',
    teacherNote: 'Order matters in students\' minds. Show the worked tower of indices before they shortcut.',
    threeDType: 'percentage_bar_3d',
    difficulty: 'core',
  },
  {
    id: 'numerical-standard-form-small',
    unit: 'numerical',
    unitLabel: unitLabels.numerical,
    strand: 'Standard form',
    topic: 'Writing small numbers in standard form',
    title: 'Standard form for tiny numbers',
    inquiryQuestion: 'How do scientists write very small measurements without a string of zeros?',
    objective: 'Convert a small decimal into A × 10ⁿ where 1 ≤ A < 10 and n is a negative integer.',
    prompt: 'Move the decimal point until only one non-zero digit is in front; the negative exponent records how many places you moved right.',
    question: 'Write 0.00045 in standard form.',
    expectedAnswer: '4.5 × 10⁻⁴',
    acceptedKeywords: ['4.5x10-4', '4.5×10-4', '4.5*10^-4', '4.5e-4'],
    correctFeedback: 'Correct. 0.00045 = 4.5 × 10⁻⁴. The exponent is negative because we moved the point right (the original was smaller than 1).',
    partialFeedback: 'Count how many places you move the decimal point to put one non-zero digit on its own. Moving right → negative exponent.',
    teacherNote: 'Pair with a large-number example so students see negative vs positive exponents on the same page.',
    threeDType: 'percentage_bar_3d',
    difficulty: 'core',
  },
  {
    id: 'numerical-standard-form-large',
    unit: 'numerical',
    unitLabel: unitLabels.numerical,
    strand: 'Standard form',
    topic: 'Writing large numbers in standard form',
    title: 'Standard form for huge numbers',
    inquiryQuestion: 'Why is it easier to compare 6 × 10⁹ and 7 × 10⁸ than 6 000 000 000 and 700 000 000?',
    objective: 'Convert a large number into A × 10ⁿ where 1 ≤ A < 10 and n is a positive integer.',
    prompt: 'Move the decimal point left until only one digit sits in front of it. The exponent counts the moves.',
    question: 'Write 73 000 000 in standard form.',
    expectedAnswer: '7.3 × 10⁷',
    acceptedKeywords: ['7.3x10^7', '7.3×10^7', '7.3*10^7', '7.3e7'],
    correctFeedback: 'Correct. The decimal point moves seven places left, giving 7.3 × 10⁷.',
    partialFeedback: 'Count the places you move the decimal until there is exactly one non-zero digit in front of it.',
    teacherNote: 'Stress the range constraint: A must satisfy 1 ≤ A < 10 (not 73 × 10⁶).',
    threeDType: 'percentage_bar_3d',
    difficulty: 'core',
  },
  {
    id: 'numerical-fdpr-conversion',
    unit: 'numerical',
    unitLabel: unitLabels.numerical,
    strand: 'FDPR',
    topic: 'Fractions, decimals, percentages',
    title: 'Three ways to say the same number',
    inquiryQuestion: 'Why might one form be more useful than another?',
    objective: 'Convert fluently between equivalent fractions, decimals and percentages.',
    prompt: 'Use ÷ for fraction to decimal, ×100 for decimal to percentage. Reverse for the other direction.',
    question: 'Write 0.75 as a fraction in simplest form and as a percentage.',
    expectedAnswer: '3/4 and 75%',
    acceptedKeywords: ['3/4', '75%', '0.75'],
    correctFeedback: 'Correct. 0.75 = 75/100 = 3/4, and 0.75 × 100 = 75%.',
    partialFeedback: 'To convert a decimal to a fraction, write it over the right power of 10 (100 here) and simplify. For percentage, multiply by 100.',
    teacherNote: 'Use the PercentageBar3D scene to anchor that 75 cubes out of 100 = 3 out of 4 = 0.75 = 75%.',
    threeDType: 'percentage_bar_3d',
    difficulty: 'support',
  },
  {
    id: 'numerical-percentage-of-amount',
    unit: 'numerical',
    unitLabel: unitLabels.numerical,
    strand: 'FDPR',
    topic: 'Percentage of an amount',
    title: 'Finding a percentage',
    inquiryQuestion: 'How can we use 10% to find any other percentage?',
    objective: 'Calculate a percentage of an amount using a benchmark strategy or direct multiplication.',
    prompt: 'Find 10% first, then scale up. Or multiply by the decimal equivalent.',
    question: 'Find 15% of 240.',
    expectedAnswer: '36',
    acceptedKeywords: ['=36', '36'],
    correctFeedback: 'Correct. 10% of 240 is 24. Half of that (5%) is 12. So 15% = 24 + 12 = 36. Or directly: 0.15 × 240 = 36.',
    partialFeedback: 'Find 10% first (divide by 10), then add 5% (half of 10%).',
    teacherNote: 'Build mental fluency before bringing in the calculator method.',
    threeDType: 'percentage_bar_3d',
    difficulty: 'support',
  },
  {
    id: 'numerical-direct-proportion',
    unit: 'numerical',
    unitLabel: unitLabels.numerical,
    strand: 'Proportion',
    topic: 'Direct proportion',
    title: 'Scale up together',
    inquiryQuestion: 'When two quantities go up together at the same rate, what equation links them?',
    objective: 'Solve direct proportion problems using the unitary method.',
    prompt: 'Find the value of one unit first, then scale up.',
    question: '4 identical pens cost AED 18. What is the cost of 7 pens?',
    expectedAnswer: 'AED 31.50',
    acceptedKeywords: ['31.5', '31.50', 'aed31.5'],
    correctFeedback: 'Correct. One pen costs 18 ÷ 4 = AED 4.50, so 7 pens cost 7 × 4.50 = AED 31.50.',
    partialFeedback: 'Divide to find the cost of one item, then multiply by the new quantity.',
    teacherNote: 'Connect to gradient (cost per pen) and y = mx form to bridge into linear relationships.',
    threeDType: 'ratio_mixer_3d',
    difficulty: 'core',
  },
  {
    id: 'numerical-inverse-proportion',
    unit: 'numerical',
    unitLabel: unitLabels.numerical,
    strand: 'Proportion',
    topic: 'Inverse proportion',
    title: 'More workers, less time',
    inquiryQuestion: 'When one quantity grows and the other shrinks, what stays constant?',
    objective: 'Solve simple inverse proportion problems by recognising that the product remains constant.',
    prompt: 'In inverse proportion, the product of the two quantities is constant.',
    question: '6 builders take 10 days to finish a wall. How long would 4 builders take, working at the same rate?',
    expectedAnswer: '15 days',
    acceptedKeywords: ['15days', '=15', '15'],
    correctFeedback: 'Correct. Total work = 6 × 10 = 60 worker-days. With 4 builders: 60 ÷ 4 = 15 days.',
    partialFeedback: 'Multiply workers × days to find the total "worker-days". Then divide by the new number of workers.',
    teacherNote: 'Contrast with direct proportion: here multiplying one by 2 means dividing the other by 2.',
    threeDType: 'ratio_mixer_3d',
    difficulty: 'core',
  },
  {
    id: 'numerical-ratio-sharing',
    unit: 'numerical',
    unitLabel: unitLabels.numerical,
    strand: 'Ratio',
    topic: 'Sharing in a ratio',
    title: 'Splitting in a 2:3 ratio',
    inquiryQuestion: 'How many parts is the whole made of?',
    objective: 'Share a quantity in a given ratio by finding the value of one part.',
    prompt: 'Add the ratio numbers to find the total parts; divide the amount by total parts to find one part; multiply by each share.',
    question: 'Share AED 200 between Ali and Sara in the ratio 2 : 3.',
    expectedAnswer: 'Ali AED 80, Sara AED 120',
    acceptedKeywords: ['80,120', '80and120', 'ali80', 'sara120'],
    correctFeedback: 'Correct. Total parts 2 + 3 = 5; one part = 200 ÷ 5 = 40. So Ali gets 2 × 40 = 80 and Sara gets 3 × 40 = 120.',
    partialFeedback: 'Add the ratio numbers first to get the total parts. Divide the amount by that total to find one part.',
    teacherNote: 'Use the RatioMixer3D scene to make "one part" tangible — two cylinders filling at different rates.',
    threeDType: 'ratio_mixer_3d',
    difficulty: 'core',
  },

  // ─── SPATIAL REASONING ──────────────────────────────────────────────
  {
    id: 'spatial-pythagoras-hypotenuse',
    unit: 'spatial',
    unitLabel: unitLabels.spatial,
    strand: 'Pythagoras',
    topic: 'Finding the hypotenuse',
    title: 'a² + b² = c²',
    inquiryQuestion: 'Why does the square on the longest side always equal the sum of the other two?',
    objective: 'Calculate the hypotenuse of a right-angled triangle using Pythagoras\' theorem.',
    prompt: 'Square the two shorter sides, add, then take the positive square root.',
    question: 'A right-angled triangle has legs of 6 cm and 8 cm. Find the hypotenuse.',
    expectedAnswer: '10 cm',
    acceptedKeywords: ['10cm', '=10', 'c=10'],
    correctFeedback: 'Correct. 6² + 8² = 36 + 64 = 100, so c = √100 = 10 cm.',
    partialFeedback: 'Square both legs, add them, then take the square root. Remember the answer is a length (always positive).',
    teacherNote: 'Anchor with the visual Pythagoras3D scene: the two smaller squares physically combine into the larger one.',
    threeDType: 'pythagoras_3d',
    difficulty: 'core',
  },
  {
    id: 'spatial-pythagoras-missing-leg',
    unit: 'spatial',
    unitLabel: unitLabels.spatial,
    strand: 'Pythagoras',
    topic: 'Finding a shorter side',
    title: 'Rearranging Pythagoras',
    inquiryQuestion: 'How does the formula change when the hypotenuse is the known side?',
    objective: 'Find a missing shorter side by rearranging Pythagoras\' theorem.',
    prompt: 'Subtract the known leg squared from the hypotenuse squared, then take the root.',
    question: 'The hypotenuse of a right-angled triangle is 13 cm and one leg is 5 cm. Find the other leg.',
    expectedAnswer: '12 cm',
    acceptedKeywords: ['12cm', '=12'],
    correctFeedback: 'Correct. 13² − 5² = 169 − 25 = 144, so the missing leg is √144 = 12 cm.',
    partialFeedback: 'When the hypotenuse is known, you subtract (not add) before square-rooting.',
    teacherNote: 'Common error: students still add. Stress that the hypotenuse² is the biggest, so the others must add to it.',
    threeDType: 'pythagoras_3d',
    difficulty: 'core',
  },
  {
    id: 'spatial-trig-sine',
    unit: 'spatial',
    unitLabel: unitLabels.spatial,
    strand: 'Right-angled trigonometry',
    topic: 'Sine ratio (SOH)',
    title: 'sin = opp / hyp',
    inquiryQuestion: 'Why do the ratios in similar right-angled triangles stay the same?',
    objective: 'Calculate sin θ given two sides of a right-angled triangle.',
    prompt: 'Identify the opposite side and the hypotenuse for angle θ.',
    question: 'In a right-angled triangle, the side opposite angle θ is 3 and the hypotenuse is 5. Find sin θ.',
    expectedAnswer: 'sin θ = 3/5 = 0.6',
    acceptedKeywords: ['3/5', '0.6', 'sinθ=0.6'],
    correctFeedback: 'Correct. sin θ = opposite / hypotenuse = 3 / 5 = 0.6.',
    partialFeedback: 'SOH: Sine = Opposite / Hypotenuse. Make sure you pick the side opposite the named angle.',
    teacherNote: 'Mnemonic SOH-CAH-TOA. Always identify hypotenuse first (opposite the right angle).',
    threeDType: 'pythagoras_3d',
    difficulty: 'core',
  },
  {
    id: 'spatial-trig-find-side',
    unit: 'spatial',
    unitLabel: unitLabels.spatial,
    strand: 'Right-angled trigonometry',
    topic: 'Finding a side using trig',
    title: 'Use the angle to find a length',
    inquiryQuestion: 'Given an angle and one side, can we find the others?',
    objective: 'Use a trigonometric ratio to find an unknown side.',
    prompt: 'Pick SOH, CAH or TOA based on which sides are known and unknown.',
    question: 'In a right-angled triangle, angle θ = 30°, the hypotenuse is 10. Find the opposite side.',
    expectedAnswer: '5',
    acceptedKeywords: ['=5', 'opp=5', '5cm'],
    correctFeedback: 'Correct. sin 30° = opp / 10, so opp = 10 × sin 30° = 10 × 0.5 = 5.',
    partialFeedback: 'Which ratio uses opposite and hypotenuse? Sine. Rearrange to opp = hyp × sin θ.',
    teacherNote: 'Use exact values (sin 30° = 1/2, cos 60° = 1/2, tan 45° = 1) to build feel before calculators.',
    threeDType: 'pythagoras_3d',
    difficulty: 'core',
  },
  {
    id: 'spatial-circle-circumference',
    unit: 'spatial',
    unitLabel: unitLabels.spatial,
    strand: 'Circles',
    topic: 'Circumference',
    title: 'Around the circle',
    inquiryQuestion: 'Why is the circumference always about 3.14 times the diameter, no matter the size?',
    objective: 'Calculate the circumference of a circle given its radius.',
    prompt: 'C = 2πr. Use π ≈ 3.14 unless told otherwise.',
    question: 'A circle has radius 7 cm. Find its circumference (use π ≈ 3.14).',
    expectedAnswer: 'about 43.96 cm',
    acceptedKeywords: ['43.96', '43.9', '≈44', '~44', '14π'],
    correctFeedback: 'Correct. C = 2π × 7 = 14π ≈ 43.96 cm.',
    partialFeedback: 'Use C = 2πr. Substitute r = 7 carefully and multiply.',
    teacherNote: 'Bring out π as a ratio (circumference ÷ diameter) using string and a coffee tin.',
    threeDType: 'circle_lab_3d',
    difficulty: 'core',
  },
  {
    id: 'spatial-circle-area',
    unit: 'spatial',
    unitLabel: unitLabels.spatial,
    strand: 'Circles',
    topic: 'Area of a circle',
    title: 'Square the radius',
    inquiryQuestion: 'What does πr² actually measure?',
    objective: 'Calculate the area of a circle using A = πr².',
    prompt: 'Square the radius first, then multiply by π.',
    question: 'A circle has radius 4 cm. Find its area (use π ≈ 3.14).',
    expectedAnswer: 'about 50.24 cm²',
    acceptedKeywords: ['50.24', '50.2', '≈50.24', '16π'],
    correctFeedback: 'Correct. A = π × 4² = 16π ≈ 50.24 cm².',
    partialFeedback: 'Square the radius (4² = 16), then multiply by π.',
    teacherNote: 'Common error: students compute (4π)² instead of πr². The radius is what gets squared, not π.',
    threeDType: 'circle_lab_3d',
    difficulty: 'core',
  },
  {
    id: 'spatial-volume-cuboid',
    unit: 'spatial',
    unitLabel: unitLabels.spatial,
    strand: '3D shapes',
    topic: 'Volume of a cuboid',
    title: 'V = length × width × height',
    inquiryQuestion: 'How many unit cubes fit inside a box?',
    objective: 'Calculate the volume of a cuboid.',
    prompt: 'Multiply the three perpendicular edge lengths.',
    question: 'A cuboid has length 8 cm, width 5 cm and height 3 cm. Find its volume.',
    expectedAnswer: '120 cm³',
    acceptedKeywords: ['120cm³', '120 cm3', '120cm3', '=120'],
    correctFeedback: 'Correct. V = 8 × 5 × 3 = 120 cm³.',
    partialFeedback: 'Multiply all three dimensions together. Units should be cm³ (a volume).',
    teacherNote: 'Use a unit cube to count one layer, then count layers — that physical model lives in SolidGeometry3D.',
    threeDType: 'solid_geometry_3d',
    difficulty: 'core',
  },
  {
    id: 'spatial-volume-cylinder',
    unit: 'spatial',
    unitLabel: unitLabels.spatial,
    strand: '3D shapes',
    topic: 'Volume of a cylinder',
    title: 'A stack of circles',
    inquiryQuestion: 'How is a cylinder like a stack of circular pancakes?',
    objective: 'Calculate the volume of a cylinder using V = πr²h.',
    prompt: 'Find the area of the circular base first, then multiply by the height.',
    question: 'A cylinder has radius 5 cm and height 10 cm. Find its volume (use π ≈ 3.14).',
    expectedAnswer: 'about 785 cm³',
    acceptedKeywords: ['785', '250π', '≈785'],
    correctFeedback: 'Correct. Base area = π × 5² = 25π. Volume = 25π × 10 = 250π ≈ 785 cm³.',
    partialFeedback: 'Volume of a prism = base area × height. The base of a cylinder is a circle.',
    teacherNote: 'Cylinder is a special prism. Visualise stacking many thin discs.',
    threeDType: 'solid_geometry_3d',
    difficulty: 'core',
  },
  {
    id: 'spatial-surface-area-cuboid',
    unit: 'spatial',
    unitLabel: unitLabels.spatial,
    strand: '3D shapes',
    topic: 'Surface area of a cuboid',
    title: 'Wrap the box',
    inquiryQuestion: 'If you unfolded a box, what shapes would you see?',
    objective: 'Calculate the total surface area of a cuboid by summing the six faces.',
    prompt: 'A cuboid has three pairs of identical faces. Find each rectangle\'s area, double it, and sum the three.',
    question: 'A cuboid measures 4 × 5 × 6 cm. Find its total surface area.',
    expectedAnswer: '148 cm²',
    acceptedKeywords: ['148cm²', '148', '=148'],
    correctFeedback: 'Correct. 2(4×5) + 2(5×6) + 2(4×6) = 40 + 60 + 48 = 148 cm².',
    partialFeedback: 'There are three pairs of identical rectangles. Add the areas of three different rectangles, then double the total.',
    teacherNote: 'Show the net unfolding (SolidGeometry3D supports this). Net = ordered list of all six rectangles.',
    threeDType: 'solid_geometry_3d',
    difficulty: 'core',
  },
  {
    id: 'spatial-metric-conversion',
    unit: 'spatial',
    unitLabel: unitLabels.spatial,
    strand: 'Measurement',
    topic: 'Metric conversion (area and volume)',
    title: 'How many cm³ in 1 m³?',
    inquiryQuestion: 'Why does the conversion factor change when you go from length to area to volume?',
    objective: 'Convert volumes between cm³ and m³ correctly.',
    prompt: 'For volume, cube the linear conversion factor.',
    question: 'How many cubic centimetres are in 1 cubic metre?',
    expectedAnswer: '1 000 000 cm³',
    acceptedKeywords: ['1000000', '1,000,000', '1million', '10^6', '1e6'],
    correctFeedback: 'Correct. 1 m = 100 cm, so 1 m³ = 100³ cm³ = 1 000 000 cm³.',
    partialFeedback: 'For volume, raise the linear conversion factor (100) to the power 3, not 1.',
    teacherNote: 'Anchor with a physical 1 cm cube stacked in a 1 m cube — instant intuition for "× 100 × 100 × 100".',
    threeDType: 'solid_geometry_3d',
    difficulty: 'extension',
  },
  {
    id: 'spatial-angles-triangle-sum',
    unit: 'spatial',
    unitLabel: unitLabels.spatial,
    strand: 'Angle reasoning',
    topic: 'Angles in a triangle',
    title: 'Triangle angle sum',
    inquiryQuestion: 'Why do the three angles of any triangle always add to 180°?',
    objective: 'Use the triangle angle sum to find a missing angle.',
    prompt: 'The three angles inside a triangle always add to 180°.',
    question: 'Two angles of a triangle are 65° and 72°. Find the third angle.',
    expectedAnswer: '43°',
    acceptedKeywords: ['43°', '=43', '43degrees'],
    correctFeedback: 'Correct. 180 − 65 − 72 = 43°.',
    partialFeedback: 'Subtract the two known angles from 180° to find the third.',
    teacherNote: 'Use the AngleLab3D scene to show a triangle being torn and reassembled along a straight line (180°).',
    threeDType: 'angle_lab_3d',
    difficulty: 'support',
  },
  {
    id: 'spatial-parallel-line-angles',
    unit: 'spatial',
    unitLabel: unitLabels.spatial,
    strand: 'Angle reasoning',
    topic: 'Parallel lines and a transversal',
    title: 'Corresponding angles',
    inquiryQuestion: 'How does a single transversal create pairs of equal and supplementary angles?',
    objective: 'Identify corresponding, alternate and co-interior angles formed by parallel lines and a transversal.',
    prompt: 'Corresponding angles are equal. Alternate (Z) angles are equal. Co-interior angles sum to 180°.',
    question: 'Two parallel lines are cut by a transversal. One of the angles measures 110°. What is the corresponding angle on the other line?',
    expectedAnswer: '110°',
    acceptedKeywords: ['110°', '110', '=110'],
    correctFeedback: 'Correct. Corresponding angles are equal when the lines are parallel.',
    partialFeedback: 'Identify the pair: same side of the transversal AND same side of the parallel line. Those are equal.',
    teacherNote: 'Use coloured arrows on a diagram. The AngleLab3D parallel-line mode visualises this directly.',
    threeDType: 'angle_lab_3d',
    difficulty: 'core',
  },
  {
    id: 'spatial-congruence-similarity',
    unit: 'spatial',
    unitLabel: unitLabels.spatial,
    strand: 'Transformations',
    topic: 'Similarity vs congruence',
    title: 'Same shape, different sizes',
    inquiryQuestion: 'When are two shapes "the same"?',
    objective: 'Distinguish between congruent and similar shapes by comparing side ratios and angles.',
    prompt: 'Congruent: same shape AND same size. Similar: same shape, sides in proportion.',
    question: 'Triangle A has sides 3, 4, 5. Triangle B has sides 6, 8, 10. Are the triangles congruent, similar, or neither?',
    expectedAnswer: 'similar (each side of B is twice the matching side of A)',
    acceptedKeywords: ['similar'],
    correctFeedback: 'Correct. Every side of B is exactly twice the corresponding side of A, so the triangles are similar with scale factor 2.',
    partialFeedback: 'Check the ratios: 6/3, 8/4, 10/5. If all the ratios are equal, the shapes are similar.',
    teacherNote: 'Common confusion: "similar" in maths is precise, not vague. Equal ratios + equal angles.',
    threeDType: 'angle_lab_3d',
    difficulty: 'core',
  },

  // ─── REASONING WITH DATA ────────────────────────────────────────────
  {
    id: 'data-mean',
    unit: 'data',
    unitLabel: unitLabels.data,
    strand: 'Measures of centre',
    topic: 'Mean',
    title: 'Finding the mean',
    inquiryQuestion: 'What does the mean tell us that individual values do not?',
    objective: 'Calculate the mean of a small data set.',
    prompt: 'Mean = (sum of all values) ÷ (number of values).',
    question: 'Find the mean of: 4, 8, 6, 10, 12.',
    expectedAnswer: '8',
    acceptedKeywords: ['=8', 'mean8', 'mean=8'],
    correctFeedback: 'Correct. Sum = 40; count = 5; mean = 40 ÷ 5 = 8.',
    partialFeedback: 'Add up all the numbers, then divide by how many numbers there are.',
    teacherNote: 'Show the mean as the "balance point" of the data — the DataVisualisation3D scene marks it visually.',
    threeDType: 'data_visualisation_3d',
    difficulty: 'support',
  },
  {
    id: 'data-median-mode',
    unit: 'data',
    unitLabel: unitLabels.data,
    strand: 'Measures of centre',
    topic: 'Median and mode',
    title: 'Middle and most common',
    inquiryQuestion: 'When is the median a better summary than the mean?',
    objective: 'Find the median and mode of a small data set.',
    prompt: 'Order the data first. Median = middle value (or mean of the two middle). Mode = most frequent.',
    question: 'For the data 3, 7, 7, 9, 12, find the median and the mode.',
    expectedAnswer: 'median 7, mode 7',
    acceptedKeywords: ['median7', 'mode7', 'median=7', '7and7'],
    correctFeedback: 'Correct. The data is already ordered; the middle value is the 3rd, which is 7. The most frequent value is also 7.',
    partialFeedback: 'Sort the values first. The median is the middle one. The mode is the value that appears most often.',
    teacherNote: 'Use an odd-length list before introducing even-length (averaging two middle values).',
    threeDType: 'data_visualisation_3d',
    difficulty: 'core',
  },
  {
    id: 'data-range',
    unit: 'data',
    unitLabel: unitLabels.data,
    strand: 'Spread',
    topic: 'Range',
    title: 'How spread out?',
    inquiryQuestion: 'Why is range a quick but limited measure of spread?',
    objective: 'Calculate the range of a data set.',
    prompt: 'Range = largest value − smallest value.',
    question: 'Find the range of: 12, 18, 7, 25, 14.',
    expectedAnswer: '18',
    acceptedKeywords: ['=18', 'range18'],
    correctFeedback: 'Correct. The largest is 25 and the smallest is 7, so the range is 25 − 7 = 18.',
    partialFeedback: 'Subtract the smallest value from the largest. The range is one number, not a list.',
    teacherNote: 'Range is sensitive to outliers — a great segue into IQR in later years.',
    threeDType: 'data_visualisation_3d',
    difficulty: 'support',
  },
  {
    id: 'data-bivariate-correlation',
    unit: 'data',
    unitLabel: unitLabels.data,
    strand: 'Bivariate data',
    topic: 'Correlation type',
    title: 'Reading a scatter plot',
    inquiryQuestion: 'What does the shape of a scatter plot tell us about the relationship between two variables?',
    objective: 'Describe the type of correlation shown by a scatter plot in words.',
    prompt: 'Look at the overall trend: up = positive; down = negative; no pattern = none.',
    question: 'A scatter plot shows hours studied on the x-axis and test score on the y-axis. Points generally rise from bottom-left to top-right. Describe the correlation.',
    expectedAnswer: 'positive correlation',
    acceptedKeywords: ['positivecorrelation', 'positive'],
    correctFeedback: 'Correct. As one variable increases, so does the other — that is positive correlation.',
    partialFeedback: 'Look at the overall pattern. Points rising from left to right means positive correlation.',
    teacherNote: 'Carefully distinguish correlation from causation. Cover the classic ice-cream-and-sunburn example.',
    threeDType: 'data_visualisation_3d',
    difficulty: 'core',
  },
  {
    id: 'data-causation-vs-correlation',
    unit: 'data',
    unitLabel: unitLabels.data,
    strand: 'Bivariate data',
    topic: 'Causation vs correlation',
    title: 'Does one cause the other?',
    inquiryQuestion: 'Why can two things move together without one causing the other?',
    objective: 'Explain the difference between correlation and causation with an example.',
    prompt: 'Correlated variables move together; causation requires that one actually causes the other.',
    question: 'Ice-cream sales and shark attacks both rise in summer. Does eating ice cream cause shark attacks? Explain.',
    expectedAnswer: 'No — both are caused by a third factor (warm weather → more beachgoers).',
    acceptedKeywords: ['no', 'weather', 'thirdfactor', 'beachgoers', 'lurkingvariable', 'commoncause'],
    correctFeedback: 'Correct. Both rise because of a third factor (hot weather → more swimmers and more ice-cream buyers). Correlation ≠ causation.',
    partialFeedback: 'Think about what else is happening. Could a third variable be driving both?',
    teacherNote: 'A great inquiry conversation. Encourage students to find their own pair of correlated-but-unrelated variables.',
    threeDType: 'data_visualisation_3d',
    difficulty: 'extension',
  },
  {
    id: 'data-probability-coin',
    unit: 'data',
    unitLabel: unitLabels.data,
    strand: 'Probability',
    topic: 'Probability of independent events',
    title: 'Two heads in a row',
    inquiryQuestion: 'How does the probability of multiple events compare to the probability of one?',
    objective: 'Calculate the probability of two independent events both occurring.',
    prompt: 'For independent events, multiply the probabilities.',
    question: 'A fair coin is flipped twice. What is the probability of getting two heads?',
    expectedAnswer: '1/4 = 0.25',
    acceptedKeywords: ['1/4', '0.25', '25%'],
    correctFeedback: 'Correct. P(H) × P(H) = 1/2 × 1/2 = 1/4. Or list outcomes: HH, HT, TH, TT — one of four.',
    partialFeedback: 'Multiply the two probabilities (1/2 × 1/2), or list all four equally-likely outcomes.',
    teacherNote: 'Show both methods (multiplication and sample space) — students learn the link between them.',
    threeDType: 'probability_spinner_3d',
    difficulty: 'core',
  },
  {
    id: 'data-probability-spinner',
    unit: 'data',
    unitLabel: unitLabels.data,
    strand: 'Probability',
    topic: 'Probability from a spinner',
    title: 'Sector area = probability',
    inquiryQuestion: 'How is the chance of landing on a sector linked to its area on the spinner?',
    objective: 'Calculate theoretical probability from a spinner with unequal sectors.',
    prompt: 'Probability = favourable sector area ÷ total area.',
    question: 'A spinner has three sectors: red 180°, blue 90°, green 90°. What is the probability of landing on green?',
    expectedAnswer: '1/4 = 0.25',
    acceptedKeywords: ['1/4', '0.25', '25%'],
    correctFeedback: 'Correct. 90° out of 360° gives 90/360 = 1/4.',
    partialFeedback: 'Divide the green sector\'s angle by 360°.',
    teacherNote: 'Use ProbabilitySpinner3D for an animated experimental run alongside the theoretical calculation.',
    threeDType: 'probability_spinner_3d',
    difficulty: 'core',
  },
  {
    id: 'data-sample-vs-population',
    unit: 'data',
    unitLabel: unitLabels.data,
    strand: 'Sampling',
    topic: 'Sample vs population',
    title: 'When is a sample enough?',
    inquiryQuestion: 'How do statisticians draw conclusions about everyone without asking everyone?',
    objective: 'Distinguish between a sample and a population and identify a representative sample.',
    prompt: 'A population is the whole group; a sample is a subset used to estimate the whole.',
    question: 'A school has 600 students. The maths teacher surveys 60 of them about study habits. What is the sample, and what is the population?',
    expectedAnswer: 'Sample: 60 students surveyed. Population: all 600 students.',
    acceptedKeywords: ['sample60', 'population600', '60and600'],
    correctFeedback: 'Correct. The 60 surveyed students form the sample; the entire group of 600 is the population.',
    partialFeedback: 'A sample is the smaller group actually surveyed. The population is the entire group we want to learn about.',
    teacherNote: 'Discuss what makes a sample representative — random selection, size, and avoiding bias.',
    threeDType: 'data_visualisation_3d',
    difficulty: 'support',
  },
];

export function findQuestionById(id: string): CurriculumQuestion | undefined {
  return grade8Curriculum.find((question) => question.id === id);
}

export function checkAnswer(question: CurriculumQuestion, answer: string): boolean {
  const normalized = answer.toLowerCase().replace(/\s+/g, '');
  return question.acceptedKeywords.some((hint) => normalized.includes(hint.toLowerCase().replace(/\s+/g, '')));
}

export function questionsByUnit(unit: CurriculumUnit): CurriculumQuestion[] {
  return grade8Curriculum.filter((q) => q.unit === unit);
}
