// Per-platform analytics schema. Each entry tells the import pipeline how to
// recognise columns, what event type to emit by default, and which normaliser
// to run. Adding a new platform is one new entry — the rest of the pipeline
// adapts automatically.

import type { ExternalPlatform, ExternalPlatformAnalyticsSchema } from './types';

export const platformAnalyticsRegistry: Record<ExternalPlatform, ExternalPlatformAnalyticsSchema> = {
  kahoot: {
    platform: 'kahoot',
    displayName: 'Kahoot',
    category: 'quiz',
    supportedMethods: ['xlsx', 'api', 'lti'],
    identityFields: {
      studentName: ['participant', 'participant name', 'nickname', 'player', 'name', 'username'],
      email: ['email', 'student email'],
    },
    activityFields: {
      activityTitle: ['game title', 'kahoot title', 'quiz title', 'kahoot', 'quiz'],
      topic: ['topic', 'subject', 'tag'],
      date: ['date', 'played at', 'created at', 'finished', 'started at'],
    },
    performanceFields: {
      score: ['score', 'total score', 'points', 'total points'],
      maxScore: ['max score', 'max points'],
      percentage: ['percentage', 'accuracy'],
      correctCount: ['correct', 'correct answers'],
      incorrectCount: ['incorrect', 'wrong answers'],
    },
    engagementFields: {
      answerTimeSeconds: ['answer time', 'time', 'time taken', 'avg answer time'],
      numberOfQuestions: ['questions', 'question count', 'total questions'],
    },
    questionFields: {
      questionText: ['question', 'question text'],
      selectedAnswer: ['answer', 'submitted answer', 'student answer'],
      correctAnswer: ['correct answer'],
      isCorrect: ['is correct'],
    },
    defaultEventType: 'question_response',
    defaultSubject: 'Mathematics',
    defaultGrade: 'Grade 8',
    normalizer: 'kahoot',
  },

  blooket: {
    platform: 'blooket',
    displayName: 'Blooket',
    category: 'game_based_learning',
    supportedMethods: ['xlsx', 'csv'],
    identityFields: {
      studentName: ['student', 'student name', 'player', 'name', 'username'],
      email: ['email'],
    },
    activityFields: {
      activityTitle: ['homework title', 'game title', 'blooket', 'set name', 'title'],
      topic: ['topic', 'subject'],
      date: ['date', 'played on', 'completed'],
    },
    performanceFields: {
      score: ['score', 'points'],
      percentage: ['accuracy', 'percentage'],
      correctCount: ['correct'],
      incorrectCount: ['incorrect'],
      unattemptedCount: ['unattempted', 'skipped'],
      completionStatus: ['completion', 'status'],
    },
    engagementFields: {
      timePlayed: ['time played', 'time', 'duration'],
      numberOfQuestions: ['questions', 'question count'],
    },
    questionFields: {
      questionText: ['question'],
      selectedAnswer: ['answer'],
      correctAnswer: ['correct answer'],
      isCorrect: ['correct'],
    },
    defaultEventType: 'live_game',
    defaultSubject: 'Mathematics',
    defaultGrade: 'Grade 8',
    normalizer: 'blooket',
  },

  drfrost: {
    platform: 'drfrost',
    displayName: 'Dr Frost',
    category: 'math_practice',
    supportedMethods: ['csv', 'xlsx'],
    identityFields: {
      studentName: ['student', 'name', 'student name', 'pupil'],
      email: ['email'],
      className: ['class', 'class name', 'group'],
    },
    activityFields: {
      activityTitle: ['worksheet', 'assessment', 'task', 'activity', 'title'],
      topic: ['topic', 'concept', 'skill', 'tag'],
      date: ['date', 'completed', 'submitted at'],
    },
    performanceFields: {
      score: ['score', 'mark'],
      maxScore: ['max', 'max score', 'total marks'],
      percentage: ['percentage', '%'],
      attemptNumber: ['attempt', 'attempts'],
      completionStatus: ['completed', 'status'],
    },
    engagementFields: {
      durationSeconds: ['duration', 'time spent'],
    },
    questionFields: {
      questionText: ['question'],
      selectedAnswer: ['answer'],
      correctAnswer: ['correct answer'],
      isCorrect: ['correct', 'is correct'],
    },
    defaultEventType: 'homework_completion',
    defaultSubject: 'Mathematics',
    defaultGrade: 'Grade 8',
    normalizer: 'drfrost',
  },

  myimaths: {
    platform: 'myimaths',
    displayName: 'MyiMaths',
    category: 'homework',
    supportedMethods: ['csv', 'xlsx'],
    identityFields: {
      studentName: ['student', 'name', 'pupil name'],
      email: ['email'],
      className: ['class', 'class name', 'group'],
    },
    activityFields: {
      activityTitle: ['task', 'homework', 'activity', 'title'],
      topic: ['curriculum area', 'topic', 'concept'],
      date: ['date', 'completed at', 'due date'],
    },
    performanceFields: {
      score: ['score'],
      percentage: ['percentage', '%'],
      attemptNumber: ['attempts'],
      completionStatus: ['completion', 'status'],
    },
    engagementFields: {
      durationSeconds: ['time spent', 'duration'],
    },
    questionFields: {},
    defaultEventType: 'homework_completion',
    defaultSubject: 'Mathematics',
    defaultGrade: 'Grade 8',
    normalizer: 'myimaths',
  },

  managebac: {
    platform: 'managebac',
    displayName: 'ManageBac',
    category: 'lms',
    supportedMethods: ['api', 'oneroster', 'csv'],
    identityFields: {
      studentName: ['student', 'name'],
      email: ['email'],
      className: ['class', 'course', 'group'],
    },
    activityFields: {
      activityTitle: ['assessment', 'task', 'assignment', 'title'],
      subject: ['subject'],
      grade: ['grade', 'year group'],
      date: ['date', 'submitted at', 'due date'],
    },
    performanceFields: {
      score: ['score', 'mark'],
      maxScore: ['max', 'max score', 'total'],
      percentage: ['percentage', '%'],
      completionStatus: ['status', 'completion'],
    },
    engagementFields: {},
    questionFields: {},
    defaultEventType: 'assessment_result',
    defaultSubject: 'Mathematics',
    defaultGrade: 'Grade 8',
    normalizer: 'managebac',
  },

  neuroquest: {
    platform: 'neuroquest',
    displayName: 'NeuroQuest Academy',
    category: 'game_based_learning',
    supportedMethods: ['api', 'manual', 'demo'],
    identityFields: {
      studentName: ['student', 'player'],
    },
    activityFields: {
      activityTitle: ['game', 'mission'],
      topic: ['topic', 'concept'],
    },
    performanceFields: {
      score: ['score'],
      accuracy: ['accuracy'],
    },
    engagementFields: {
      durationSeconds: ['time played'],
    },
    questionFields: {},
    defaultEventType: 'live_game',
    defaultSubject: 'Mathematics',
    defaultGrade: 'Grade 8',
    normalizer: 'generic',
  },

  eis_maths_studio: {
    platform: 'eis_maths_studio',
    displayName: 'EIS Maths Studio',
    category: 'lms',
    supportedMethods: ['api', 'demo'],
    identityFields: {
      studentName: ['student'],
    },
    activityFields: {
      activityTitle: ['lesson', 'assignment'],
      topic: ['topic'],
    },
    performanceFields: {
      score: ['score'],
    },
    engagementFields: {},
    questionFields: {},
    defaultEventType: 'assignment_submission',
    defaultSubject: 'Mathematics',
    defaultGrade: 'Grade 8',
    normalizer: 'generic',
  },

  manual_csv: {
    platform: 'manual_csv',
    displayName: 'Generic CSV / XLSX',
    category: 'custom',
    supportedMethods: ['csv', 'xlsx'],
    identityFields: {},
    activityFields: {},
    performanceFields: {},
    engagementFields: {},
    questionFields: {},
    defaultEventType: 'question_response',
    defaultSubject: 'Mathematics',
    defaultGrade: 'Grade 8',
    normalizer: 'generic',
  },

  // Future platforms — registered but not yet wired to dedicated normalizers.
  google_classroom: {
    platform: 'google_classroom',
    displayName: 'Google Classroom',
    category: 'lms',
    supportedMethods: ['api', 'oneroster'],
    identityFields: { email: ['email'], studentName: ['name', 'student'] },
    activityFields: { activityTitle: ['assignment'], subject: ['subject'] },
    performanceFields: { score: ['score'], maxScore: ['max score'] },
    engagementFields: {},
    questionFields: {},
    defaultEventType: 'assignment_submission',
    defaultSubject: 'Mathematics',
    defaultGrade: 'Grade 8',
    normalizer: 'generic',
  },
  microsoft_teams: {
    platform: 'microsoft_teams',
    displayName: 'Microsoft Teams Assignments',
    category: 'lms',
    supportedMethods: ['api', 'oneroster'],
    identityFields: { email: ['email'], studentName: ['student'] },
    activityFields: { activityTitle: ['assignment'] },
    performanceFields: { score: ['score'], maxScore: ['points possible'] },
    engagementFields: {},
    questionFields: {},
    defaultEventType: 'assignment_submission',
    defaultSubject: 'Mathematics',
    defaultGrade: 'Grade 8',
    normalizer: 'generic',
  },
  quizizz: {
    platform: 'quizizz',
    displayName: 'Quizizz',
    category: 'quiz',
    supportedMethods: ['csv', 'xlsx', 'api'],
    identityFields: { studentName: ['name', 'student', 'participant'], email: ['email'] },
    activityFields: { activityTitle: ['quiz name', 'activity', 'title'], topic: ['topic'] },
    performanceFields: { score: ['score', 'points'], percentage: ['accuracy', 'percentage'] },
    engagementFields: { durationSeconds: ['time spent', 'duration'] },
    questionFields: {
      questionText: ['question'],
      selectedAnswer: ['response', 'answer'],
      correctAnswer: ['correct answer'],
      isCorrect: ['correct'],
    },
    defaultEventType: 'question_response',
    defaultSubject: 'Mathematics',
    defaultGrade: 'Grade 8',
    normalizer: 'generic',
  },
  edpuzzle: {
    platform: 'edpuzzle',
    displayName: 'Edpuzzle',
    category: 'video_learning',
    supportedMethods: ['api', 'csv'],
    identityFields: { studentName: ['student'], email: ['email'] },
    activityFields: { activityTitle: ['video', 'assignment'] },
    performanceFields: { percentage: ['watched', '%'] },
    engagementFields: { durationSeconds: ['time spent'] },
    questionFields: {},
    defaultEventType: 'video_watch',
    defaultSubject: 'Mathematics',
    defaultGrade: 'Grade 8',
    normalizer: 'generic',
  },
  seneca: {
    platform: 'seneca',
    displayName: 'Seneca Learning',
    category: 'homework',
    supportedMethods: ['csv', 'api'],
    identityFields: { studentName: ['student'], email: ['email'] },
    activityFields: { activityTitle: ['assignment'], topic: ['topic'] },
    performanceFields: { percentage: ['score', 'accuracy'] },
    engagementFields: { durationSeconds: ['time'] },
    questionFields: {},
    defaultEventType: 'homework_completion',
    defaultSubject: 'Mathematics',
    defaultGrade: 'Grade 8',
    normalizer: 'generic',
  },
  mathspace: {
    platform: 'mathspace',
    displayName: 'Mathspace',
    category: 'math_practice',
    supportedMethods: ['csv', 'api'],
    identityFields: { studentName: ['student'], email: ['email'] },
    activityFields: { activityTitle: ['task'], topic: ['topic', 'strand'] },
    performanceFields: { percentage: ['accuracy'], score: ['score'] },
    engagementFields: { durationSeconds: ['time spent'] },
    questionFields: {},
    defaultEventType: 'homework_completion',
    defaultSubject: 'Mathematics',
    defaultGrade: 'Grade 8',
    normalizer: 'generic',
  },
  wonde: {
    platform: 'wonde',
    displayName: 'Wonde MIS Bridge',
    category: 'lms',
    supportedMethods: ['api', 'oneroster'],
    identityFields: { studentName: ['student'], email: ['email'] },
    activityFields: {},
    performanceFields: {},
    engagementFields: {},
    questionFields: {},
    defaultEventType: 'assessment_result',
    defaultSubject: 'Mathematics',
    defaultGrade: 'Grade 8',
    normalizer: 'generic',
  },
  custom: {
    platform: 'custom',
    displayName: 'Custom Platform',
    category: 'custom',
    supportedMethods: ['csv', 'xlsx', 'manual'],
    identityFields: {},
    activityFields: {},
    performanceFields: {},
    engagementFields: {},
    questionFields: {},
    defaultEventType: 'question_response',
    defaultSubject: 'Mathematics',
    defaultGrade: 'Grade 8',
    normalizer: 'generic',
  },
};

export const platformList: ExternalPlatform[] = Object.keys(
  platformAnalyticsRegistry,
) as ExternalPlatform[];
