// Honest per-connector registry. Every entry tells the UI what the real
// support level is today and what the school admin needs to enable to lift
// the status from drive_ingestion to API.

import type { ConnectorPlatform, ConnectorRegistryItem } from './types';

export const connectorRegistry: Record<ConnectorPlatform, ConnectorRegistryItem> = {
  kahoot: {
    platform: 'kahoot',
    displayName: 'Kahoot',
    category: 'official_api',
    recommendedMethod: 'api',
    fallbackMethod: 'drive_folder',
    status: 'ready',
    description:
      'Official Reports API available for authorised customers. Drive-folder ingestion remains the safe fallback while EIS finalises API access.',
    setupInstructions: [
      'Confirm the EIS Kahoot plan supports the Reports API (Kahoot 360 / Enterprise).',
      'Request a client ID + client secret from Kahoot admin / API access.',
      'Store both secrets server-side in Google Secret Manager.',
      'Set a nightly sync schedule (default 02:00 Asia/Dubai).',
      'Map Kahoot participants to the ManageBac / EIS roster.',
    ],
    requiresSchoolAdmin: true,
    requiresVendorApproval: true,
    supportsAutomaticSync: true,
    supportsDriveIngestion: true,
    supportedData: 'reports',
    relatedLearningHubPlatform: 'kahoot',
  },
  managebac: {
    platform: 'managebac',
    displayName: 'ManageBac',
    category: 'school_system',
    recommendedMethod: 'api',
    fallbackMethod: 'oneroster',
    status: 'ready',
    description:
      'ManageBac is the school system of record. Direct API + OneRoster sync gives roster identity that every other connector references.',
    setupInstructions: [
      'School admin enables the ManageBac Public API.',
      'Create a token with least-privilege roster + class permissions.',
      'Store the token in Google Secret Manager.',
      'Sync students, teachers, classes, enrollments.',
      'Use the synced roster as the identity source for imported learning events.',
    ],
    requiresSchoolAdmin: true,
    requiresVendorApproval: false,
    supportsAutomaticSync: true,
    supportsDriveIngestion: false,
    supportedData: 'roster',
    relatedLearningHubPlatform: 'managebac',
  },
  google_drive: {
    platform: 'google_drive',
    displayName: 'Google Drive Import Folder',
    category: 'drive_ingestion',
    recommendedMethod: 'drive_folder',
    status: 'ready',
    description:
      'School-approved shared Drive folder. Teachers drop exports into platform subfolders; Learning Data Hub picks them up automatically. Acts as the universal bridge for export-only platforms.',
    setupInstructions: [
      'Create a shared Drive folder owned by the EIS Google Workspace.',
      'Create subfolders: Kahoot, Blooket, Dr Frost, MyiMaths, ManageBac, Generic.',
      'Grant a Workspace service account read access (or use domain-wide delegation).',
      'Teachers export reports into the matching subfolder.',
      'Cloud Run sync picks up new files nightly and routes them to the right normaliser.',
    ],
    requiresSchoolAdmin: true,
    requiresVendorApproval: false,
    supportsAutomaticSync: true,
    supportsDriveIngestion: true,
    supportedData: 'mixed',
    relatedLearningHubPlatform: 'manual_csv',
  },
  blooket: {
    platform: 'blooket',
    displayName: 'Blooket',
    category: 'export_only',
    recommendedMethod: 'drive_folder',
    fallbackMethod: 'manual_export',
    status: 'drive_ready',
    description:
      'CSV/XLSX reports today. Public API not confirmed — Drive ingestion is the production path until Blooket grants enterprise / partner access.',
    setupInstructions: [
      'Export Blooket game / homework reports.',
      'Save into the shared Drive · Blooket subfolder.',
      'Drive connector imports automatically and normalises through the Blooket schema.',
      'Optional: request Blooket enterprise / partner API access for live sync.',
    ],
    requiresSchoolAdmin: false,
    requiresVendorApproval: true,
    supportsAutomaticSync: false,
    supportsDriveIngestion: true,
    supportedData: 'reports',
    relatedLearningHubPlatform: 'blooket',
  },
  myimaths: {
    platform: 'myimaths',
    displayName: 'MyiMaths',
    category: 'export_only',
    recommendedMethod: 'drive_folder',
    fallbackMethod: 'manual_export',
    status: 'drive_ready',
    description:
      'Markbook / class results export available. Public API not confirmed — Drive ingestion is the production path until MyiMaths grants vendor access.',
    setupInstructions: [
      'Export MyiMaths Markbook / class results from the teacher dashboard.',
      'Save into the shared Drive · MyiMaths subfolder.',
      'Drive connector imports the file automatically and normalises through the MyiMaths schema.',
      'Optional: request MyiMaths API / partner access for live sync.',
    ],
    requiresSchoolAdmin: false,
    requiresVendorApproval: true,
    supportsAutomaticSync: false,
    supportsDriveIngestion: true,
    supportedData: 'gradebook',
    relatedLearningHubPlatform: 'myimaths',
  },
  drfrost: {
    platform: 'drfrost',
    displayName: 'Dr Frost',
    category: 'export_only',
    recommendedMethod: 'drive_folder',
    fallbackMethod: 'vendor_partner',
    status: 'drive_ready',
    description:
      'Wonde / ManageBac handles roster identity. Results API / partner access requires approval; until then Drive ingestion of worksheet / assessment reports is the production path.',
    setupInstructions: [
      'Use Wonde or ManageBac for roster identity.',
      'Export Dr Frost worksheet / assessment reports.',
      'Save into the shared Drive · Dr Frost subfolder.',
      'Request Dr Frost API / partner access for direct result sync.',
    ],
    requiresSchoolAdmin: true,
    requiresVendorApproval: true,
    supportsAutomaticSync: false,
    supportsDriveIngestion: true,
    supportedData: 'reports',
    relatedLearningHubPlatform: 'drfrost',
  },
  wonde: {
    platform: 'wonde',
    displayName: 'Wonde MIS Bridge',
    category: 'roster_mis',
    recommendedMethod: 'api',
    status: 'planned',
    description:
      'Roster / MIS bridge. Once the school commits to Wonde, this connector pulls students, year groups, classes, enrollments and feeds them into the identity layer.',
    setupInstructions: [
      'School approves the Wonde connection at the MIS level.',
      'Generate a Wonde API token with read scope.',
      'Store the token in Google Secret Manager.',
      'Sync roster, year groups, classes, enrollments.',
      'Use Wonde identities for student matching across every learning platform.',
    ],
    requiresSchoolAdmin: true,
    requiresVendorApproval: false,
    supportsAutomaticSync: true,
    supportsDriveIngestion: false,
    supportedData: 'roster',
    relatedLearningHubPlatform: 'wonde',
  },
  generic: {
    platform: 'generic',
    displayName: 'Generic CSV / XLSX',
    category: 'drive_ingestion',
    recommendedMethod: 'drive_folder',
    status: 'drive_ready',
    description:
      'Any platform that exports CSV / XLSX. Drop into the Generic subfolder; teachers can map unknown columns inside the Hub if needed.',
    setupInstructions: [
      'Export any CSV / XLSX report.',
      'Save into the shared Drive · Generic subfolder.',
      'Use the Column Mapper in Upload Reports if the layout is unusual.',
    ],
    requiresSchoolAdmin: false,
    requiresVendorApproval: false,
    supportsAutomaticSync: true,
    supportsDriveIngestion: true,
    supportedData: 'mixed',
    relatedLearningHubPlatform: 'manual_csv',
  },
};

export const connectorList: ConnectorPlatform[] = Object.keys(connectorRegistry) as ConnectorPlatform[];
